name: mening_budgetim
description: "Приложение для учета личных финансов в Казахстане"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # UI & Charts
  cupertino_icons: ^1.0.2
  fl_chart: ^0.65.0
  intl: ^0.19.0
  
  # Networking
  http: ^1.1.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Testing
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true